### ISSUE TITLE
init function is not called

### ISSUE THREAD

**Issue by uhotspot4** [mattkhaw/cordova-plugin-callkit#1]
Let me first thank you for the merging of those two plugins.

Here is my javascript code of my ionic/react capacitor project:

    var push = VoIPPushNotification.init();
    push.on('registration', function(data) {
        console.log("Registered VOIP push.");
        console.log(data);
    });

It seems that registration function is never called.

I have added a log into the beginning of VoIPPushNotification.js file and it is printed out.
But then the following logs are not printed:

    module.exports = {  
        init: function(options) {
            console.log("Init function called.....");
            return new VoIPPushNotification(options);
        },
        VoIPPushNotification: VoIPPushNotification
    };

and this one...

    push.on('notification', function(data) {
        console.log("[Ionic] notification callback called");
        console.log(data);
    
    });

And also the breakpoint at the beginning of following function in VoIPPushNotification.m is never reached:

    - (void)init:(CDVInvokedUrlCommand*)command
    {
      self.VoIPPushCallbackId = command.callbackId;
      NSLog(@"[objC] callbackId: %@", self.VoIPPushCallbackId);

      //http://stackoverflow.com/questions/27245808/implement-pushkit-and-test-in-development-   behavior/28562124#28562124
      PKPushRegistry *pushRegistry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
      pushRegistry.delegate = self;
      pushRegistry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
    }

Following is what I see in the Xcode console although I haven't called CordovaCall!

    APP ACTIVE
    To Native Cordova ->  CordovaCall init CordovaCall1212087107 ["options": []]
    2020-07-14 22:20:16.236592-0700 myTestApp[779:87575] [objC] callbackId: CordovaCall1212087107
    WebView loaded
    ⚡️  To Native ->  App addListener 22887397

Can you please let me know what I could have possibly done wrong?

Thanks.

**Comment by mattkhaw** [comment]
After reading all this, seems fine to me if you can call the functions from the plugin. The most common problem with Ionic/React Capacitor is the plugin doesn't install correctly, which is not the case here since you can call the functions.

To answer why CordovaCall is logged during the launch of the app is because CordovaCall automatically inits itself on load. It is the default behaviour. Don't worry about that.

As for why VoIP push is not calling back, I think the problem mostly lies on the setup from the Apple Developer console. Maybe you should check your settings thru the console just to make sure it is set up correctly. Have you checked whether the capability is enabled as well in your project? Not sure it will help but it might be that too although the chances of it happening is pretty low since the plugin automatically enables all the capabilities required.

Sorry for the lack of knowledge in Ionic/React Capacitor since I didn't use these frameworks much if the answer I've given is too barebones. I doubt that the plugin is not called during deviceReady because from the log that you've posted here, it seems to be called there but it is worth checking out as well just to make sure that you've called the plugin in the correct place.

**Comment by uhotspot4** [comment]
Thanks for your answer. 
I double checked the settings and they all seem to be OK to the best of my knowledge as follow:

- I have checked "Push Notification" as the capability for my app on Apple Developer portal (don't know if that is even necessary or not, but anyway)
- And in the Xcode capabilities for my app I have the following capabilities checked:

1. Audio, Airplay and picture in picture
2. Voice over IP
3. Background fetch
4. Remote Notification
5. Background Processing

I'm very very new to javascript/react/ionic so pardon me if my question sounds silly.

When I call the following code

    var push = VoIPPushNotification.init();

Is it supposed to call the init function in

    module.exports = {  
        init: function(options) {
            console.log("Init function called.....");
            return new VoIPPushNotification(options);
        },
        VoIPPushNotification: VoIPPushNotification
    };

Because to me that is the very first thing that should have been called and if yes what other function calls or sequence of functions/processes could be between me calling init and the latter mentioned init being called?
That might help me figuring out where in the chain the problem exists.

**Comment by uhotspot4** [comment]
Thanks for your answer.
One more question. Do I need to have both CordovaCall and cordova-ios-voip-push installed prior to installing yours? Or your plugin is a standalone one containing everything it needs?
I don't see VoIPPushNotification.h or VoIPPushNotification.m in your project!

**Comment by uhotspot4** [comment]
I don't know if this says anything or not but CordovaCall works pretty ok!

    cordova.plugins.CordovaCall.receiveCall('John Smith');

**Comment by mattkhaw** [comment]
If you are using my plugin, no. As stated in the repo, both CordovaCall and VoIP push is combined together into one. Reason why those files are not here is because it is already mixed into CordovaCall but the namespace remains the same.

To answer your next question, as stated in my previous reply, if you can call the functions, it is installed properly. Just make sure you are setting it up properly.

**Comment by mattkhaw** [comment]
So, did you solve the issue?
