### ISSUE TITLE
Answering phone crashes the app

### ISSUE THREAD

**Issue by mashrurbd** [mattkhaw/cordova-plugin-callkit#16]
In Android 10, answering phone crashes the app.

**Comment by mattkhaw** [comment]
For issues like this, I suggest you ask here instead => [https://github.com/WebsiteBeaver/CordovaCall](https://github.com/WebsiteBeaver/CordovaCall) since this plugin is based on that project.

AFAIK, I've used this plugin exclusively on Android 10 and I don't have any issues. Maybe you can double check your code again and see what causes the crash.

**Comment by HugoHeneault** [comment]
@mashrurbd Giving some logs might definitively be useful when you're having issues with open source projects :-)

**Comment by mattkhaw** [comment]
> @mashrurbd Giving some logs might definitively be useful when you're having issues with open source projects :-)

yeah, that would help to trace the error as well.

**Comment by mattkhaw** [comment]
Closed due to inactivity.

**Comment by mashrurbd** [comment]
So you can't solve a problem and close it? Lol! so called developers!

**Comment by mattkhaw** [comment]
@mashrurbd The issue was closed due to inactivity. I've already mentioned that there's no issues on the devices I've tested and I'm using it in my production apps. Also, did you provide any logs for further debugging? I don't see them at all and also, since you are so god dang smart, solve the problem yourself then. I'm not your personal butler.

**Comment by mashrurbd** [comment]
Well, share the production app's link then. Let me check on my device.

**Comment by mattkhaw** [comment]
I don't need to and it won't work standalone anyways. Ignoring this.

Good luck.
