### ISSUE TITLE
[Help wanted] Firebasex plugin integration

### ISSUE THREAD

**Issue by wnabil** [mattkhaw/cordova-plugin-callkit#8]
Hello,
I want to use CallKit with [Firebasex plugin](https://github.com/dpa99c/cordova-plugin-firebasex) but i was hoping you to advice me if this plugin is needed or not in that case.
I am planning to use [CordovaCall plugin](https://github.com/WebsiteBeaver/CordovaCall) + firebasex plugin so as i imagine i do not need [cordova-ios-voip-push](https://github.com/Hitman666/cordova-ios-voip-push) to handle the notifications but i only need to configuration the project to allow background mods for voip/background fetch and remote notification so this means i do not need this current plugin as well or is there anything else i will need this plugin for ?
Any help is appreciated and many thanks for your effort.

**Comment by mozhn** [comment]
This cordova plugin as It allows us to show the call acceptance screen without writing code in your application for ios. On Android, the situation is a little more complicated. I used [FCM](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated). After installing this plugin, you will need to make changes to your file in this [link](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/blob/1c43714f878c54c048ca1fbfeba8fb5dfe16df12/src/android/com/gae/scaffolder/plugin/MyFirebaseMessagingService.java#L34). Here, it will be enough to write the code that will start the application. I hope I could help.

**Comment by wnabil** [comment]
Thanks for the info, i will close this issue for now and keep you updated about my try with firebasex plugin
i have to use firebasex in order to support crashlytics and many other firebase features so i am looking to integrate it with CordovaCall then will get in touch with you if i needed anything, many thanks your help is really appreciated

**Comment by mattkhaw** [comment]
@wnabil As stated by @mozhn , this plugin is designed solely to work with APNS VOIP push notification for iOS. As for Android, I don't see the need to add push notification support natively since it can be done easily with background notifications. If you want to use Firebasex for iOS, I highly suggest you read through their documentation on implementing VOIP push notifications. AFAIK, 3rd party push notifications are very hit and miss for VOIP support. I've tried OneSignal's and it doesn't work at all. Some people are using AWS. Seems to be working for that. The best way is using APNS directly. As for Android, as long as you are using background notifications, you should be good.
